"""Password Alter migration

Revision ID: 1b179bb77b51
Revises: f367b0d6ef71
Create Date: 2024-10-02 21:34:22.203777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b179bb77b51'
down_revision = 'f367b0d6ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.BigInteger(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
