"""Expire Minutes Addition

Revision ID: 36d84aab86e6
Revises: 1b179bb77b51
Create Date: 2024-10-02 23:16:33.390496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d84aab86e6'
down_revision = '1b179bb77b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expire_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('expire_minutes')

    # ### end Alembic commands ###
